(int) @sexp
(float) @sexp
(bigint) @sexp
(bigdec) @sexp
(string) @sexp
(symbol) @sexp
(list) @sexp
(vector) @sexp
(map) @sexp
(set) @sexp
(call) @sexp
(block_call) @sexp
(method_call) @sexp
(field_access) @sexp
(metadata) @sexp
