(int) @sexp
(float) @sexp
(bigint) @sexp
(bigdec) @sexp
(string) @sexp
(symbol) @sexp
(list) @sexp
(vector) @sexp
(record) @sexp
(set) @sexp
(call) @sexp
(record_sugar) @sexp
(block_call) @sexp
(metadata) @sexp
